### ISSUE TITLE
Dailies

### ISSUE THREAD

**Issue by Memry** [Aras14HD/habitica_challenge-from-csv#5]
I have not been able to get the daily option to function successfully.  I can create Habits and To-Dos without trouble, but as soon as I add a daily, it fails.  It's possible my input data is wrong, but I've followed the formula exactly.  

Here is a copy of a file I am using to test.

52 Weeks of Eating Healthy, Week 52 (Dec 26 - Jan 1)
:bento:Week 52
This challenge is to test dailies and habits - I need to get the daily thing working okay.
ac7da919-7751-4694-9c03-1234c40d64b3
1
habit;:bento:Week 52: :bomb: ate when I wasn't hungry;;Easy;2022-01-01;
habit;:bento:Week 52: menu planned and hordes fed!;;Hard;2022-01-01;
daily;:bento:Week 52: What's for dinner tomorrow?;;Medium;2021-12-26;Weekly;1;mtwthfssu;
habit;:bento:Week 52: Tried a new recipe;;Hard;2022-01-01;
habit;:bento:Week 52: Aded a new menu plan to my repertoire;;Hard;2022-01-01;
todo;:bento:Week 52: Reported to the guild;necessary for winning the challenge!;Easy;2022-01-01;

As soon as I remove the daily line, it works fine.  I have also tried replacing Weekly with Daily on the line, removing the end of the line completely.  I am not certain if I have an error in the formatting.  I don't have an example copy to use for comparison - if I did, I might be able to correct my file.

**Comment by Aras14HD** [comment]
Well I see three things wrong with that line:
1. there shouldn't be a number after "Weekly;"
2. the days should be comma separated (m,t,w,th,f,s,su)
3. "Weekly" should be written "weekly"

But I'll be sure to make the Documentation/Guide more descriptive and easier to understand, and I'll make it give more helpful errors.

Sorry for replying so late, I was on holiday without access to my PC and Github didn't email me about the issue!
