### ISSUE TITLE
Description don't fit with the code

### ISSUE THREAD

**Issue by JerryC436** [Aras14HD/habitica_challenge-from-csv#6]
According to the description, 

> ...tasks of the type Daily can be daily, weekly, monthly, or **yearly**. They have special requirements: ...

a Daily could repeat "yearly". Plus, you can choose to set a Daily that repeats "yearly" in Habitica, and the parameters are basically the same as setting it "daily". 

Yet when you try to use "yearly" instead of "daily", error messages appear like this:

> # Error:Unknown frequency type (task type daily) "yearly"
> Valid frequency types: "daily", "weekly", "monthly"

**Comment by Aras14HD** [comment]
Should be fixed now. (used like daily)

Don't know, why it was missing.
